### ISSUE TITLE
Portierungen nach Qt5 und Qt6

### ISSUE THREAD

**Issue by tnbp** [Funzinator/von-neumann-emulator#2]
Hallo Herr Beppler, ich habe mir erlaubt, den Simulator nach Qt5 zu portieren (ein paar Compiler-Warnungen) und auch nach Qt6 (hier waren ein paar Zeilen mehr nötig). Die Änderungen sind in einem geforkten Repository zu finden (mit Branches master (Qt5) und qt6).
Herr Jakobi lässt Sie herzlich grüßen. Von ihm stammt auch die Änderung in include/Storage.h.
Falls Sie das möchten, kann ich einen PR erstellen.

Liebe Grüße

**Comment by Funzinator** [comment]
Hallo,
Das gleiche habe ich auch einmal angegangen, dann aber aufgegeben. Sehr schön, dass es vollendet werden konnte.

~~Sehr gern PR!~~

Edit: Ich war so frei: https://github.com/Funzinator/von-neumann-emulator/pull/3

**Comment by tnbp** [comment]
Cool! Der `master`-Branch enthält allerdings nur die kleinen Änderungen für Qt5; die etwas größeren sind im `qt6`-Branch.

**Comment by Funzinator** [comment]
Gut, dann mache ich den wieder zu und eröffne ihn direkt mit Qt6.
